# Kilograms
mass : 1.9891e+30

# fractions (out of 1)
mass_fractions:
  X : .7
  Y : .28
  Z : .02

#Kelvin
effective_temperature: 5777.

# Kilograms / meter^3
calculate_pressue: true
average_pressure: 1410.

# Meters
radius:
  step:  1.0e+3
  total: 7.0e+8
