# Kilograms
mass : 1.0

# fractions (out of 1)
mass_fractions:
  X : .7
  Y : .28
  Z : .02

#Kelvin
effective_temperature: 5777

# Kilograms
average_pressure: 1410

# Meters
radii_filename: "data/radii"
