# Kilograms
mass : 1.9891e+30

# fractions (out of 1)
mass_fractions:
  X : .7
  Y : .28
  Z : .02

# Meters
radius:
  dr:  1.0e+3
  total: 7.0e+8

# check units of opacity
opacity:
  filename: "./opacity.txt"